#!/bin/sh
set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$ROOT_DIR"

say() {
  printf '\n== %s ==\n' "$1"
}

need_file() {
  if [ ! -s "$1" ]; then
    printf 'missing required file: %s\n' "$1" >&2
    exit 1
  fi
}

say "required docs"
need_file README.md
need_file LICENSE
need_file SECURITY.md
need_file CONTRIBUTING.md
need_file docs/SETUP.md
need_file docs/FLASHING.md
need_file docs/SYSTEM.md
need_file docs/FIREWALL-HOWTO.md
need_file docs/DEVICE_PROFILES.md
need_file docs/MCP.md
need_file docs/TRADEMARKS.md
need_file docs/WIFI.md
need_file docs/assets/setup-wizard.png
need_file docs/assets/setup-mobile.png
need_file docs/assets/dashboard-overview.png
need_file docs/assets/dashboard-ports.png
printf 'ok\n'

say "python syntax"
python3 -m py_compile app.py scripts/mx65ctl.py mcp/myracke_mcp.py
printf 'ok\n'

say "javascript syntax"
node --check static/app.js
node --check static/manage.js
node --check router-manager/www/mx65/app.js
printf 'ok\n'

say "shell syntax"
for script in scripts/*.sh router-manager/www/cgi-bin/mx65-api; do
  sh -n "$script"
done
printf 'ok\n'

say "mcp smoke"
python3 -c 'import json, subprocess, sys; msgs=[{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"readiness","version":"1"}}},{"jsonrpc":"2.0","method":"notifications/initialized","params":{}},{"jsonrpc":"2.0","id":2,"method":"tools/list","params":{}}]; payload=b"".join([b"Content-Length: "+str(len(json.dumps(m).encode())).encode()+b"\r\n\r\n"+json.dumps(m).encode() for m in msgs]); p=subprocess.run([sys.executable,"mcp/myracke_mcp.py"],input=payload,capture_output=True,timeout=5); out=p.stdout.decode("utf-8","replace"); assert p.returncode == 0, p.stderr.decode("utf-8","replace"); assert "myracke_preflight" in out and "myracke_harden_security" in out, out; print("ok")'

say "large files"
large_files=$(
  git ls-files | while IFS= read -r file; do
    if [ -f "$file" ] && [ "$(wc -c < "$file")" -gt 5242880 ]; then
      printf '%s\n' "$file"
    fi
  done
)
if [ -n "$large_files" ]; then
  printf '%s\n' "$large_files" >&2
  exit 1
fi
printf 'ok\n'

say "forbidden generated artifacts"
forbidden_files=$(git ls-files | grep -E '(\.key|\.token|\.bin|\.img|\.tgz|\.pem|\.tar\.gz)$' || :)
if [ -n "$forbidden_files" ]; then
  printf '%s\n' "$forbidden_files" >&2
  exit 1
fi
printf 'ok\n'

say "secret text scan"
if git grep -nE 'OPENSSH PRIVATE KEY|BEGIN PRIVATE KEY|BEGIN RSA PRIVATE KEY|CLOUDFLARE_TOKEN=|mx65-manager-[0-9.]+\.token' -- \
  . \
  ':!data' \
  ':!downloads' \
  ':!backups' \
  ':!docs/assets' \
  ':!scripts/repo-readiness-check.sh'; then
  printf 'secret-like text found\n' >&2
  exit 1
fi
printf 'ok\n'

say "tool attribution scan"
if git grep -nE 'C[o]dex|ChatG[P]T|OpenA[I]|A[I] generated|generated by A[I]|assist[a]nt' -- \
  . \
  ':!data' \
  ':!downloads' \
  ':!backups' \
  ':!docs/assets' \
  ':!scripts/repo-readiness-check.sh'; then
  printf 'tool attribution text found\n' >&2
  exit 1
fi
printf 'ok\n'

say "public hygiene scan"
if git grep -nEI 'K[a]reem|e[l]kwae|K[a]reemsKodes|/U[s]ers/|P[r]ivAIcy|A[n]khOfTruth|D[i]neroDrive|mA[I]Models|Document Rev[i]ew|LocalD[o]c|mx65-fl[a]sh-guide|PUBLIC_READINESS|before publ[i]shing|g[o]oky|garb[a]ge|f[u]ck|sh[i]t|bullsh[i]t|T[O]DO|T[B]D|F[I]XME|v[i]be|10[.]69[.]69' -- \
  . \
  ':!data' \
  ':!downloads' \
  ':!backups' \
  ':!docs/assets' \
  ':!scripts/repo-readiness-check.sh'; then
  printf 'public-readiness hygiene issue found\n' >&2
  exit 1
fi
printf 'ok\n'

say "summary"
printf 'repo readiness checks passed\n'
